var hierarchy =
[
    [ "_SLK", "struct__SLK.html", null ],
    [ "NCursesApplication::_slk_link", "structNCursesApplication_1_1__slk__link.html", null ],
    [ "_win_st", "struct__win__st.html", null ],
    [ "alias", "structalias.html", null ],
    [ "alias_table_data", "structalias__table__data.html", null ],
    [ "assoc", "structassoc.html", null ],
    [ "ATTR_TBL", "structATTR__TBL.html", null ],
    [ "Binding_Info", "structBinding__Info.html", null ],
    [ "BookType", "classBookType.html", null ],
    [ "color_t", "structcolor__t.html", null ],
    [ "commands", "structcommands.html", null ],
    [ "DATA", "structDATA.html", null ],
    [ "DriverEntry", "structDriverEntry.html", null ],
    [ "DYNBUF", "structDYNBUF.html", null ],
    [ "enumARG", "structenumARG.html", null ],
    [ "enumParams", "structenumParams.html", null ],
    [ "FG_NODE", "structFG__NODE.html", null ],
    [ "FieldAttrs", "structFieldAttrs.html", null ],
    [ "fieldnode", "structfieldnode.html", null ],
    [ "formnode", "structformnode.html", null ],
    [ "HashData", "structHashData.html", null ],
    [ "HASHMAP", "structHASHMAP.html", null ],
    [ "HISTORY", "structHISTORY.html", null ],
    [ "HOW_MUCH", "structHOW__MUCH.html", null ],
    [ "integerPARM", "structintegerPARM.html", null ],
    [ "interval", "structinterval.html", null ],
    [ "ITERATOR_VARS", "structITERATOR__VARS.html", null ],
    [ "kn", "structkn.html", null ],
    [ "ldat", "structldat.html", null ],
    [ "LinkedListIterator< T >", "classLinkedListIterator.html", null ],
    [ "LinkedListType< T >", "classLinkedListType.html", null ],
    [ "map", "structmap.html", null ],
    [ "MARK", "structMARK.html", null ],
    [ "MenuLines", "structMenuLines.html", null ],
    [ "MEVENT", "structMEVENT.html", null ],
    [ "MYCOLOR", "structMYCOLOR.html", null ],
    [ "MYPAIR", "structMYPAIR.html", null ],
    [ "name_table_data", "structname__table__data.html", null ],
    [ "name_table_entry", "structname__table__entry.html", null ],
    [ "NAME_VALUE", "structNAME__VALUE.html", null ],
    [ "NCURSES_GLOBALS", "structNCURSES__GLOBALS.html", null ],
    [ "NCURSES_PRESCREEN", "structNCURSES__PRESCREEN.html", null ],
    [ "NCursesApplication", "classNCursesApplication.html", [
      [ "TestApplication", "classTestApplication.html", null ]
    ] ],
    [ "NCursesException", "classNCursesException.html", [
      [ "NCursesFormException", "classNCursesFormException.html", null ],
      [ "NCursesMenuException", "classNCursesMenuException.html", null ],
      [ "NCursesPanelException", "classNCursesPanelException.html", null ]
    ] ],
    [ "NCursesFieldType", "classNCursesFieldType.html", [
      [ "Alpha_Field", "classAlpha__Field.html", null ],
      [ "Alphanumeric_Field", "classAlphanumeric__Field.html", null ],
      [ "Enumeration_Field", "classEnumeration__Field.html", null ],
      [ "IPV4_Address_Field", "classIPV4__Address__Field.html", null ],
      [ "Integer_Field", "classInteger__Field.html", null ],
      [ "Numeric_Field", "classNumeric__Field.html", null ],
      [ "Regular_Expression_Field", "classRegular__Expression__Field.html", null ],
      [ "UserDefinedFieldType", "classUserDefinedFieldType.html", [
        [ "MyFieldType", "classMyFieldType.html", null ],
        [ "UserDefinedFieldType_With_Choice", "classUserDefinedFieldType__With__Choice.html", null ]
      ] ]
    ] ],
    [ "NCursesFormField", "classNCursesFormField.html", [
      [ "Label", "classLabel.html", null ],
      [ "NCursesUserField< T >", "classNCursesUserField.html", null ]
    ] ],
    [ "NCursesMenuItem", "classNCursesMenuItem.html", [
      [ "FormAction", "classFormAction.html", null ],
      [ "NCursesMenuCallbackItem", "classNCursesMenuCallbackItem.html", null ],
      [ "NCursesUserItem< T >", "classNCursesUserItem.html", [
        [ "MyAction< T >", "classMyAction.html", null ]
      ] ],
      [ "PadAction", "classPadAction.html", null ],
      [ "PassiveItem", "classPassiveItem.html", null ],
      [ "QuitItem", "classQuitItem.html", null ],
      [ "ScanAction", "classScanAction.html", null ]
    ] ],
    [ "NCursesWindow", "classNCursesWindow.html", [
      [ "NCursesColorWindow", "classNCursesColorWindow.html", null ],
      [ "NCursesPad", "classNCursesPad.html", [
        [ "NCursesFramedPad", "classNCursesFramedPad.html", null ]
      ] ],
      [ "NCursesPanel", "classNCursesPanel.html", [
        [ "NCursesForm", "classNCursesForm.html", [
          [ "NCursesUserForm< T >", "classNCursesUserForm.html", null ],
          [ "TestForm", "classTestForm.html", null ]
        ] ],
        [ "NCursesMenu", "classNCursesMenu.html", [
          [ "MyMenu", "classMyMenu.html", null ],
          [ "NCursesUserMenu< T >", "classNCursesUserMenu.html", null ]
        ] ],
        [ "NCursesUserPanel< T >", "classNCursesUserPanel.html", null ]
      ] ]
    ] ],
    [ "NodeType< T >", "classNodeType.html", null ],
    [ "pagenode", "structpagenode.html", null ],
    [ "pair", "structpair.html", null ],
    [ "panel", "structpanel.html", null ],
    [ "panelhook", "structpanelhook.html", null ],
    [ "_win_st::pdat", "struct__win__st_1_1pdat.html", null ],
    [ "Peg", "structPeg.html", null ],
    [ "PICS_CELL", "structPICS__CELL.html", null ],
    [ "PICS_HEAD", "structPICS__HEAD.html", null ],
    [ "rgb_bits_t", "unionrgb__bits__t.html", null ],
    [ "RGB_DATA", "structRGB__DATA.html", null ],
    [ "RGB_NAME", "structRGB__NAME.html", null ],
    [ "ripoff_t", "structripoff__t.html", null ],
    [ "screen", "structscreen.html", null ],
    [ "SGR_DATA", "structSGR__DATA.html", null ],
    [ "ship_t", "structship__t.html", null ],
    [ "SillyDemo", "classSillyDemo.html", null ],
    [ "slk_ent", "structslk__ent.html", null ],
    [ "Soft_Label_Key_Set::Soft_Label_Key", "classSoft__Label__Key__Set_1_1Soft__Label__Key.html", null ],
    [ "Soft_Label_Key_Set", "classSoft__Label__Key__Set.html", null ],
    [ "speed", "structspeed.html", null ],
    [ "speeds", "structspeeds.html", null ],
    [ "STACK_FRAME", "structSTACK__FRAME.html", null ],
    [ "string_desc", "structstring__desc.html", null ],
    [ "tagITEM", "structtagITEM.html", null ],
    [ "tagMENU", "structtagMENU.html", null ],
    [ "term", "structterm.html", null ],
    [ "TERMDATA", "structTERMDATA.html", null ],
    [ "termtype", "structtermtype.html", null ],
    [ "TEXT", "structTEXT.html", null ],
    [ "TGETENT_CACHE", "structTGETENT__CACHE.html", null ],
    [ "thisARG", "structthisARG.html", null ],
    [ "thisPARM", "structthisPARM.html", null ],
    [ "tinfo_fkeys", "structtinfo__fkeys.html", null ],
    [ "token", "structtoken.html", null ],
    [ "TPARM_STATE", "structTPARM__STATE.html", null ],
    [ "TRACEBUF", "structTRACEBUF.html", null ],
    [ "typearg", "structtypearg.html", null ],
    [ "typenode", "structtypenode.html", null ],
    [ "UDF_Init", "classUDF__Init.html", null ],
    [ "user_table_data", "structuser__table__data.html", null ],
    [ "user_table_entry", "structuser__table__entry.html", null ],
    [ "UserData", "classUserData.html", null ],
    [ "NCursesForm::UserHook", "structNCursesForm_1_1UserHook.html", null ],
    [ "NCursesMenu::UserHook", "structNCursesMenu_1_1UserHook.html", null ],
    [ "NCursesPanel::UserHook", "structNCursesPanel_1_1UserHook.html", null ],
    [ "worm", "structworm.html", null ]
];